# Generated by Django 5.0.3 on 2024-03-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0004_itenscompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
